--q1.what is the total revenue generated by male vs female customers?
 select gender, SUM(purchase_amount) as revenue
 from customer_shopping_behaviour group by gender

--q2.which customer used a discount but still spent more than average purchase amount?
  select customer_id, purchase_amount from customer_shopping_behaviour
  where discount_applied ='Yes' and purchase_amount >=(select AVG(purchase_amount) from customer_shopping_behaviour);

--q3.which are the top 5 products with highest average review rating?
    select item_purchased, ROUND(AVG(review_rating)::numeric,2) as "Average Product Rating" from customer_shopping_behaviour
	group by item_purchased
	order by avg(review_rating) desc
	limit 5;

 --q4.compare the average purchase amounts between standard and express shipping.
   select shipping_type,
   ROUND(AVG(purchase_amount)::numeric,2)
   from customer_shopping_behaviour where shipping_type in ('Standard','Express') group by shipping_type
   
---q5.Do suscribed customer spend more? compare average spend and total revenue between subscribers and non-suscribers.
    Select subscription_status,
	COUNT(customer_id) as total_customers,
	ROUND(AVG(purchase_amount)::numeric,2) as avg_spend,
	ROUND(SUM(purchase_amount)::numeric,2) as total_revenue
	from customer_shopping_behaviour
	group by subscription_status
	order by total_revenue,avg_spend desc;

--q6.Which 5 products have the highest percentage of purchase with discounts applied?
     select item_purchased,
	 ROUND(SUM(CASE WHEN discount_applied ='Yes' Then 1 ELSE 0 END)::numeric/COUNT(*) * 100,2) as discount_rate from customer_shopping_behaviour
	 group by item_purchased
	 order by discount_rate desc
	 limit 5;
--q7.what are the top 3 most purchased products within each category?
   with item_counts as (
   select category,
   item_purchased,
   COUNT(customer_id) as total_orders,
   ROW_NUMBER() over(partition by category order by count(customer_id) Desc) as item_rank
   from customer_shopping_behaviour
   group by category, item_purchased
   )
   select item_rank, category,item_purchased, total_orders from item_counts
   where item_rank <= 3;